# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e268ea37a085da189fa4eb36ce046fb2741f4e980da74133573e88e42284e3ddb25e6c804163e56ee09b6f0a7c44c8bff3203f26a5f3a74d1dd7a6e10efea62

test:
  secret_key_base: 480a2d530a2b8d8bdb77a0fe93674acacfbcb1110062aebe558bc470ddbf2ebe2861bef654e4d9e56785535b7a28cac60a04541c0e48e23df816cd426e55a3b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
